Repository necst-telescope/neclib, pull requests merged in 2022-11, with the labels that each got.

#231 #230 Add process to reset config
  tests/test_configation.py
Labels: bug

#229 Add context manager for temporary parameter change
  neclib/controllers/antenna_pid.py
  tests/controllers/test_antenna_pid.py
Labels: enhancement

#233 Release v0.13.6
  pyproject.toml
Labels: release

#235 Auto-detect device modules
  neclib/devices/__init__.py
Labels: enhancement

#237 Add config key validation
  neclib/configuration.py
  tests/_data/invalid/config_duplicated_definition.toml
  tests/_data/invalid/config_reserved_name.toml
  tests/test_configation.py
Labels: enhancement

#239 #238 Update project version
  pyproject.toml
Labels: release

#241 Make `get_quantity` optionally return type validator
  neclib/typing.py
  neclib/utils/quantity_utils.py
  tests/utils/test_quantity_utils.py
Labels: enhancement

#243 Accept dimensionless weather data
  neclib/coordinates/convert.py
  tests/coordinates/test_convert.py
Labels: enhancement

#245 #244 change version to 0.13.8
  pyproject.toml
Labels: release

#249 Fix type annotations
  neclib/__init__.py
  neclib/controllers/__init__.py
  neclib/controllers/antenna_pid.py
  neclib/coordinates/convert.py
  neclib/coordinates/optimize.py
  neclib/coordinates/path_finder.py
  neclib/devices/encoder/nd287.py
  neclib/devices/weather_station/tr73u.py
  neclib/interfaces/console_logger.py
  neclib/parameters/__init__.py
  neclib/parameters/obsparam.py
  neclib/parameters/parser/obsparam_data.py
  neclib/parameters/parser/pointing_error_data.py
  neclib/parameters/pointing_error.py
  neclib/recorders/file_writer.py
  neclib/recorders/necstdb_writer.py
  neclib/recorders/recorder.py
  neclib/safety/decelerate.py
  neclib/simulators/__init__.py
  neclib/simulators/antenna.py
  neclib/typing.py
  neclib/units.py
  neclib/utils/__init__.py
  neclib/utils/data_utils.py
  neclib/utils/math_utils.py
  neclib/utils/quantity_utils.py
  tests/utils/test_quantity_utils.py
Labels: bug

#251 Refactor configuration object
  neclib/configuration.py
  neclib/devices/selector.py
  poetry.lock
  pyproject.toml
  tests/test_configation.py
Labels: enhancement

#200 #187 implement signal generator controller
  neclib/devices/signal_generator/__init__.py
  neclib/devices/signal_generator/fsw0010.py
  neclib/devices/signal_generator/fsw0020.py
  neclib/devices/signal_generator/signal_generator_base.py
  neclib/src/config.toml
  neclib/units.py
  neclib/utils/__init__.py
  neclib/utils/logic_utils.py
  pyproject.toml
  tests/utils/test_logic_utils.py
Labels: enhancement

#253 Support control of chopper motor
  .github/workflows/test.yml
  neclib/devices/device_base.py
  neclib/devices/motor/cpz7415v.py
  neclib/devices/motor/motor_base.py
  neclib/devices/selector.py
  neclib/simulators/__init__.py
  neclib/src/config.toml
  neclib/utils/__init__.py
  neclib/utils/device_utils.py
  poetry.lock
  pyproject.toml
  tests/devices/__init__.py
  tests/devices/motor/__init__.py
  tests/devices/motor/test_cpz7415v.py
  tests/devices/test_selector.py
Labels: enhancement

#255 Fix accidentally removed parameter getter
  neclib/devices/motor/cpz7415v.py
  tests/devices/motor/test_cpz7415v.py
Labels: bug

#257 Release v0.14.1
  pyproject.toml
Labels: release

#259 Change config initialization method
  neclib/devices/motor/cpz7415v.py
  neclib/devices/selector.py
  tests/devices/motor/test_cpz7415v.py
Labels: enhancement

#266 #265 add file for minimize spectral data
  .vscode/settings.json
  neclib/data/__init__.py
  neclib/data/resize.py
  tests/data/__init__.py
  tests/data/test_resize.py
Labels: enhancement

#268 Rename configuration exception
  neclib/configuration.py
  neclib/devices/device_base.py
  neclib/devices/selector.py
  neclib/exceptions.py
  pyproject.toml
  tests/test_configation.py
  tests/test_exceptions.py
Labels: invalid, release

#271 Support oblique scan and offset frame
  neclib/coordinates/__init__.py
  neclib/coordinates/convert.py
  neclib/coordinates/frame.py
  neclib/coordinates/path_finder.py
  neclib/utils/__init__.py
  neclib/utils/array_utils.py
  pyproject.toml
  tests/coordinates/test_convert.py
  tests/coordinates/test_frame.py
  tests/coordinates/test_path_finder.py
  tests/utils/test_array_utils.py
Labels: bug, enhancement

#274 Add chopper parameters
  neclib/controllers/antenna_pid.py
  neclib/devices/selector.py
  neclib/simulators/antenna.py
  neclib/src/config.toml
  pyproject.toml
Labels: enhancement

#275 #260 Update files to add `"scan"` command
  .vscode/settings.json
  neclib/configuration.py
  neclib/coordinates/path_finder.py
  neclib/src/config.toml
  tests/coordinates/test_path_finder.py
Labels: enhancement
