Repository necst-telescope/neclib, pull requests merged in 2022-12, with the labels that each got.

#272 #261 cpz3177
  neclib/devices/bias_reader/__init__.py
  neclib/devices/bias_reader/bias_reader_base.py
  neclib/devices/bias_reader/cpz3177.py
  neclib/src/config.toml
Labels: enhancement

#270 #262 cpz340816
  neclib/devices/bias_setter/__init__.py
  neclib/devices/bias_setter/bias_setter_base.py
  neclib/devices/bias_setter/cpz340816.py
  neclib/src/config.toml
Labels: enhancement

#277 Add initialization on CPZ7415V start-up
  neclib/devices/motor/cpz7415v.py
  pyproject.toml
Labels: enhancement

#280 Quick fix on unresponsive motor control
  neclib/devices/motor/cpz7415v.py
Labels: bug

#283 Make recorder singleton
  neclib/recorders/necstdb_writer.py
Labels: enhancement

#286 #285 Change gpib communication->usb communication
  neclib/devices/thermometer/model_218.py
  neclib/src/config.toml
  tests/devices/thermometer/test_model_218.py
Labels: bug

#289 #287 Delete debug print in `PathFinder`
  neclib/coordinates/path_finder.py
Labels: bug

#291 Read actual motion
  neclib/devices/motor/cpz7415v.py
Labels: bug

#297 Version 0.15.1
  pyproject.toml
Labels: release

#295 Add device controllers
  .github/release.yml
  neclib/__init__.py
  neclib/coordinates/frame.py
  neclib/devices/attenuator/__init__.py
  neclib/devices/attenuator/attenuator_base.py
  neclib/devices/attenuator/rhio10.py
  neclib/devices/motor/cpz7415v.py
  neclib/devices/power_meter/__init__.py
  neclib/devices/power_meter/ma24126a.py
  neclib/devices/power_meter/power_meter_base.py
  neclib/devices/spectrometer/__init__.py
  neclib/devices/spectrometer/spectrometer_base.py
  neclib/devices/spectrometer/xffts.py
  neclib/devices/vacuum_gauge/__init__.py
  neclib/devices/vacuum_gauge/tpg261.py
  neclib/devices/vacuum_gauge/vacuum_gauge_base.py
  neclib/recorders/console_log_writer.py
  neclib/recorders/file_writer.py
  neclib/recorders/necstdb_writer.py
  neclib/recorders/recorder.py
  neclib/recorders/writer_base.py
  neclib/src/config.toml
  pyproject.toml
  tests/devices/motor/test_cpz7415v.py
Labels: enhancement

#299 Fix parameter handling in modified PID algorithm
  neclib/controllers/antenna_pid.py
  poetry.lock
  pyproject.toml
Labels: bug

#302 Support changing constant term factor
  neclib/controllers/antenna_pid.py
Labels: enhancement

#303 Add error handler for TR-73U read-out
  neclib/controllers/antenna_pid.py
  neclib/devices/weather_station/tr73u.py
Labels: bug

#305 Version 0.15.2
  pyproject.toml
Labels: release

#308 Fix thread handling in recorder
  neclib/recorders/recorder.py
Labels: bug

#309 Fix thread management in recorder
  neclib/recorders/recorder.py
Labels: bug

#306 Version 0.15.2
  poetry.lock
  pyproject.toml
Labels: release

#315 Support log level setting via environment variable
  neclib/interfaces/console_logger.py
Labels: enhancement

#317 Version 0.15.3
  pyproject.toml
Labels: release

#313 Return generator in coordinate converter
  neclib/coordinates/convert.py
  neclib/coordinates/path_finder.py
  neclib/recorders/recorder.py
  poetry.lock
  pyproject.toml
  tests/coordinates/test_path_finder.py
Labels: enhancement

#319 Stabilize motor control
  README.md
  neclib/devices/motor/cpz7415v.py
Labels: bug

#321 Support URL in config path specification
  neclib/__init__.py
  neclib/configuration.py
  tests/test_configation.py
Labels: enhancement

#322 Fix conditionally not-functioning motor controller
  neclib/devices/bias_reader/cpz3177.py
  neclib/devices/bias_setter/cpz340816.py
  neclib/devices/device_base.py
  neclib/devices/motor/cpz7415v.py
Labels: bug

#293 Calculated considering acceleration for SCAN
  neclib/coordinates/convert.py
  neclib/coordinates/optimize.py
  neclib/coordinates/path_finder.py
  neclib/recorders/recorder.py
  tests/coordinates/test_path_finder.py
Labels: enhancement

#324 Version 0.16.0
  pyproject.toml
Labels: release

#326 Support axis name alias for motor control parameter
  neclib/devices/motor/cpz7415v.py
  neclib/utils/data_utils.py
  tests/utils/test_data_utils.py
Labels: bug

#328 Fix thread handling in `NECSTDBWriter`
  README.md
  neclib/recorders/necstdb_writer.py
Labels: bug

#331 Make recorder singleton
  neclib/recorders/recorder.py
Labels: enhancement

#332 Add file reader
  neclib/__init__.py
  neclib/configuration.py
  neclib/parameters/__init__.py
  neclib/parameters/parser/obsparam_data.py
  neclib/parameters/parser/pointing_error_data.py
  neclib/utils/__init__.py
  neclib/utils/file_utils.py
  pyproject.toml
  tests/utils/test_file_utils.py
Labels: enhancement

#334 Support multiple pointing models
  docs/conf.py
  neclib/coordinates/convert.py
  neclib/parameters/__init__.py
  neclib/parameters/parser/__init__.py
  neclib/parameters/parser/pointing_error_data.py
  neclib/parameters/pointing_error.py
  neclib/src/pointing_param.toml
  pyproject.toml
  tests/parameters/parser/test_pointing_error_data.py
Labels: enhancement

#336 Support coordinate calculation from name of celestial body
  neclib/coordinates/convert.py
  neclib/coordinates/path_finder.py
  pyproject.toml
Labels: enhancement

#338 Fix error on coordinate query with non-planet celestial body name
  neclib/coordinates/path_finder.py
Labels: bug

#340 Fix data drop procedure which possibly fails in `data.Resize`
  neclib/data/resize.py
Labels: bug

#342 Support time input in `PIDController.get_speed`
  neclib/controllers/antenna_pid.py
  neclib/coordinates/path_finder.py
Labels: enhancement

#344 Add Python object interpolator
  neclib/__init__.py
  neclib/controllers/antenna_pid.py
  neclib/data/__init__.py
  neclib/data/interpolate.py
  pyproject.toml
  tests/data/test_interpolate.py
Labels: enhancement

#346 Add extrapolate method
  neclib/data/__init__.py
  neclib/data/extrapolate.py
  neclib/data/interpolate.py
  pyproject.toml
  tests/data/test_extrapolate.py
  tests/data/test_interpolate.py
  tests/test_configuration.py
Labels: enhancement

#350 Add observer coordinate calculator
  neclib/coordinates/__init__.py
  neclib/coordinates/observer.py
Labels: enhancement

#351 Add safety measure for bias voltage setter
  neclib/devices/bias_reader/bias_reader_base.py
  neclib/devices/bias_reader/cpz3177.py
  neclib/devices/bias_setter/bias_setter_base.py
  neclib/devices/bias_setter/cpz340816.py
  neclib/src/config.toml
Labels: enhancement, invalid

#352 Change time offset management
  neclib/coordinates/path_finder.py
Labels: enhancement

#356 Version 0.17.4
  pyproject.toml
Labels: release

#354 Support device ID selection
  neclib/configuration.py
  neclib/coordinates/path_finder.py
  neclib/devices/__init__.py
  neclib/devices/ad_converter/__init__.py
  neclib/devices/ad_converter/ad_converter_base.py
  neclib/devices/ad_converter/cpz3177.py
  neclib/devices/attenuator/attenuator_base.py
  neclib/devices/attenuator/rhio10.py
  neclib/devices/da_converter/__init__.py
  neclib/devices/da_converter/cpz340816.py
  neclib/devices/da_converter/da_converter_base.py
  neclib/devices/device_base.py
  neclib/devices/encoder/encoder_base.py
  neclib/devices/encoder/nd287.py
  neclib/devices/motor/cpz7415v.py
  neclib/devices/power_meter/ma24126a.py
  neclib/devices/selector.py
  neclib/devices/signal_generator/fsw0010.py
  neclib/devices/signal_generator/fsw0020.py
  neclib/devices/signal_generator/signal_generator_base.py
  neclib/devices/spectrometer/xffts.py
  neclib/devices/thermometer/model_218.py
  neclib/devices/thermometer/thermometer_base.py
  neclib/devices/vacuum_gauge/tpg261.py
  neclib/devices/weather_station/tr73u.py
  neclib/devices/weather_station/weather_station_base.py
  neclib/src/config.toml
  neclib/utils/__init__.py
  neclib/utils/security_utils.py
  pyproject.toml
  tests/devices/test_selector.py
  tests/test_configuration.py
Labels: enhancement

#359 Faster config
  neclib/__init__.py
  neclib/configuration.py
  neclib/coordinates/path_finder.py
  neclib/devices/attenuator/rhio10.py
  neclib/devices/device_base.py
  pyproject.toml
Labels: bug, release

#361 Fix invalid namespace parsing in config
  neclib/configuration.py
  pyproject.toml
Labels: bug, release

#363 Support remote path for root directory of parameter files
  neclib/configuration.py
  pyproject.toml
Labels: enhancement, release

#365 Preserve config parameter type
  neclib/configuration.py
  pyproject.toml
  tests/test_configuration.py
Labels: bug, release

#367 Fix invalid device identifier for Model-218
  neclib/devices/device_base.py
  neclib/devices/thermometer/model_218.py
  pyproject.toml
Labels: bug, release

#369 Reduce sleep duration for signal generator read-out
  neclib/devices/signal_generator/fsw0010.py
  neclib/devices/signal_generator/fsw0020.py
  poetry.lock
  pyproject.toml
Labels: bug
