Repository necst-telescope/neclib, pull requests merged in 2022-10, with the labels that each got.

#172 Fix 'current' coordinate handling when target is given as array
  neclib/coordinates/optimize.py
  neclib/utils/__init__.py
  neclib/utils/data_utils.py
  neclib/utils/simulator_utils.py
  poetry.lock
  pyproject.toml
  tests/coordinates/test_optimize.py
  tests/recorders/test_db_writer.py
  tests/utils/test_data_utils.py
  tests/utils/test_simulator_utils.py
Labels: invalid

#177 Read both Az. and El. axes of encoders with single instance
  neclib/devices/encoder/encoder_base.py
  neclib/devices/encoder/nd287.py
  neclib/devices/motor/cpz7415v.py
  neclib/devices/selector.py
  neclib/src/config.toml
  tests/_data/sample_config_customized.toml
Labels: invalid

#179 Run astropy function to create parameter file cache
  neclib/__init__.py
Labels: enhancement

#182 Add integrated recorder, which can handle arbitrary record writer
  neclib/__init__.py
  neclib/configuration.py
  neclib/coordinates/convert.py
  neclib/coordinates/optimize.py
  neclib/devices/motor/cpz7415v.py
  neclib/devices/selector.py
  neclib/interfaces/__init__.py
  neclib/interfaces/console_logger.py
  neclib/recorders/__init__.py
  neclib/recorders/console_log_writer.py
  neclib/recorders/db_writer.py
  neclib/recorders/necstdb_writer.py
  neclib/recorders/recorder.py
  neclib/recorders/writer_base.py
  neclib/typing.py
  neclib/utils/simulator_utils.py
  tests/interfaces/test_console_logger.py
  tests/recorders/conftest.py
  tests/recorders/test_console_log_writer.py
  tests/recorders/test_necstdb_writer.py
  tests/recorders/test_recorder.py
Labels: enhancement

#183 Use `ConsoleLogger`
  neclib/recorders/writer_base.py
Labels: enhancement

#184 Implement file writer
  neclib/recorders/__init__.py
  neclib/recorders/file_writer.py
  tests/recorders/test_file_writer.py
Labels: enhancement

#189 Fix default argument
  neclib/recorders/recorder.py
  tests/recorders/test_recorder.py
Labels: bug

#191 Add speed calculator with consideration of deceleration towards drive range limit
  docs/_static/css/custom.css
  docs/_static/logo.svg
  docs/conf.py
  neclib/__init__.py
  neclib/configuration.py
  neclib/controllers/antenna_pid.py
  neclib/coordinates/optimize.py
  neclib/interfaces/console_logger.py
  neclib/safety/__init__.py
  neclib/safety/decelerate.py
  neclib/typing.py
  neclib/utils/data_utils.py
  neclib/utils/math_utils.py
  poetry.lock
  pyproject.toml
  tests/interfaces/test_console_logger.py
  tests/safety/__init__.py
  tests/safety/test_decelerate.py
  tests/test_configation.py
Labels: enhancement

#195 Add status manager
  neclib/configuration.py
  neclib/devices/encoder/nd287.py
  neclib/safety/__init__.py
  neclib/safety/status.py
  neclib/src/config.toml
  pyproject.toml
  tests/_data/sample_config_customized.toml
  tests/safety/test_status.py
Labels: enhancement

#197 Add `map` method to `ValueRange`
  neclib/configuration.py
  neclib/safety/decelerate.py
  neclib/src/config.toml
  neclib/utils/data_utils.py
  pyproject.toml
  tests/_data/sample_config_customized.toml
  tests/utils/test_data_utils.py
Labels: enhancement

#199 Add parameter and implementation reference
  docs/conf.py
  docs/index.md
  docs/parameters/index.md
  docs/tutorials/config.md
  docs/tutorials/devices.md
  docs/tutorials/index.md
  neclib/configuration.py
  neclib/devices/selector.py
  neclib/recorders/necstdb_writer.py
  neclib/utils/data_utils.py
  tests/utils/test_data_utils.py
Labels: documentation

#202 Version 0.12.7
  pyproject.toml
Labels: release

#204 Retain original object name
  .github/workflows/test.yml
  neclib/devices/selector.py
  pyproject.toml
Labels: bug

#192 add three files in weather_status
  neclib/devices/__init__.py
  neclib/devices/weather_station/__init__.py
  neclib/devices/weather_station/tr73u.py
  neclib/devices/weather_station/weather_base.py
  neclib/src/config.toml
Labels: enhancement

#206 Version 0.13.0
  pyproject.toml
Labels: release

#211 Change obstime handling in AltAz to AltAz conversion
  neclib/coordinates/convert.py
Labels: bug

#215 Fix config usage
  neclib/devices/motor/cpz7415v.py
  pyproject.toml
Labels: bug

#218 Fix parameter handling
  neclib/coordinates/convert.py
  neclib/devices/motor/cpz7415v.py
  pyproject.toml
  tests/coordinates/test_convert.py
Labels: bug

#220 Fix return type
  neclib/coordinates/convert.py
Labels: bug

#222 Version 0.13.4
  pyproject.toml
Labels: release

#217 #126 path
  neclib/coordinates/__init__.py
  neclib/coordinates/convert.py
  neclib/coordinates/path_finder.py
  tests/coordinates/test_path_finder.py
Labels: enhancement

#224 Change version restriction for ogameasure
  poetry.lock
  pyproject.toml
Labels: bug

#226 change humididy
  neclib/devices/weather_station/tr73u.py
Labels: enhancement
