Repository necst-telescope/neclib, pull requests merged in 2023-11, with the labels that each got.

#504 #503 fix pointing error of nanten2
  neclib/coordinates/pointing_error/nanten2.py
  pyproject.toml
Labels: bug, release

#508 #507 change pyproject
  pyproject.toml
Labels: release

#509 #500 optical pandas
  neclib/coordinates/observations/optical_pointing.py
  poetry.lock
  pyproject.toml
Labels: bug, enhancement
