Repository necst-telescope/neclib, pull requests merged in 2023-08, with the labels that each got.

#476 Edit pyproject and rerun poetry
  poetry.lock
  pyproject.toml
Labels: bug

#478 Change neclib version to 0.24.9
  pyproject.toml
Labels: release

#480 #469 change unit deg_C to K
  neclib/devices/thermometer/simulator.py
Labels: bug

#481 #459 add change channel function
  neclib/devices/spectrometer/xffts.py
Labels: enhancement
