Repository necst-telescope/neclib, pull requests merged in 2023-02, with the labels that each got.

#415 Add Configuration Notes of CPZ3177 used for BiasReader
  neclib/devices/ad_converter/cpz3177.py
Labels: documentation

#424 Fix missing host and port in relative path configuration
  neclib/core/configuration.py
  pyproject.toml
Labels: bug

#421 Add figure and coordinate data property to observation spec
  docs/conf.py
  neclib/__init__.py
  neclib/coordinates/observations/observation_spec_base.py
  neclib/coordinates/path_finder.py
  neclib/core/__init__.py
  neclib/core/configuration.py
  neclib/core/data_type/parameters.py
  neclib/core/data_type/rich_parameters.py
  neclib/core/exceptions.py
  neclib/core/formatting/observation_to_html.py
  neclib/core/security/__init__.py
  neclib/core/security/sanitize_impl.py
  neclib/devices/ad_converter/cpz3177.py
  neclib/devices/da_converter/cpz340816.py
  neclib/utils/__init__.py
  pyproject.toml
  tests/docs/test_build.py
Labels: enhancement, release

#425 Support OTF observation starting from certain scan number
  neclib/coordinates/observations/otf.py
  neclib/defaults/config.toml
  tests/_data/sample_otf.toml
  tests/core/security/__init__.py
  tests/core/security/test_sanitize.py
Labels: enhancement

#426 Implement computer load checker
  neclib/core/security/__init__.py
  neclib/core/security/load_check.py
  poetry.lock
  pyproject.toml
  tests/core/security/test_load_check.py
Labels: enhancement

#428 Fix invalid value update in observation time keeper
  neclib/coordinates/observations/observation_spec_base.py
Labels: bug

#434 Add loadavg checker
  neclib/core/security/load_check.py
  pyproject.toml
  tests/core/security/test_load_check.py
Labels: enhancement, release
