Repository necst-telescope/neclib, pull requests merged in 2024-04, with the labels that each got.

#520 #518 thermo gpib
  .vscode/settings.json
  neclib/defaults/config.toml
  neclib/devices/thermometer/model_218.py
  poetry.lock
  tests/devices/thermometer/test_model_218.py
Labels: bug

#522 [WIP] #521 add ml2437a.py
  neclib/defaults/config.toml
  neclib/devices/__init__.py
  neclib/devices/power_meter/__init__.py
  neclib/devices/power_meter/ml2437a.py
Labels: enhancement

#525 #523 docs
  neclib/devices/attenuator/rhio10.py
  neclib/devices/da_converter/cpz340816.py
  neclib/devices/encoder/nd287.py
  neclib/devices/power_meter/ma24126a.py
  neclib/devices/signal_generator/fsw0010.py
  neclib/devices/signal_generator/fsw0020.py
  neclib/devices/spectrometer/xffts.py
  neclib/devices/vacuum_gauge/tpg261.py
  neclib/devices/weather_station/tr73u.py
  tests/devices/ad_converter/__init__.py
  tests/devices/ad_converter/test_cpz3177.py
  tests/devices/attenuator/__init__.py
  tests/devices/attenuator/test_rhio10.py
  tests/devices/ccd_controller/__init__.py
  tests/devices/ccd_controller/test_ccd_controller.py
  tests/devices/da_converter/__init__.py
  tests/devices/da_converter/test_cpz340816.py
  tests/devices/power_meter/__init__.py
  tests/devices/power_meter/test_ma24126a.py
  tests/devices/power_meter/test_ml2437.py
  tests/devices/signal_generator/test_fsw0010.py
  tests/devices/signal_generator/test_fsw0020.py
  tests/devices/spectrometer/__init__.py
  tests/devices/spectrometer/test_xffts.py
  tests/devices/vacuum_gauge/__init__.py
  tests/devices/vacuum_gauge/test_tpg261.py
Labels: documentation, enhancement

#527 #526 release new version v0.25.2
  pyproject.toml
Labels: release

#529 #528 add LOattenuator
  neclib/defaults/config.toml
  neclib/devices/attenuator/__init__.py
  neclib/devices/attenuator/attenuator_base.py
  neclib/devices/attenuator/cpz340516.py
  neclib/devices/attenuator/rhio10.py
  neclib/devices/attenuator/simulator.py
  pyproject.toml
Labels: enhancement
