Repository necst-telescope/neclib, pull requests merged in 2024-07, with the labels that each got.

#553 #552 add parameter
  neclib/defaults/config.toml
  poetry.lock
Labels: enhancement

#549 #548 add cpz7204, cpz2724
  neclib/defaults/config.toml
  neclib/devices/membrane/__init__.py
  neclib/devices/membrane/cpz2724.py
  neclib/devices/membrane/membrane_base.py
  neclib/devices/motor/__init__.py
  neclib/devices/motor/cpz2724.py
  neclib/devices/motor/cpz7204.py
  tests/devices/membrane/test_cpz2724.py
Labels: enhancement

#567 #566 fix calculation of Vobs
  neclib/coordinates/observer.py
  tests/coordinates/test_observer.py
Labels: bug

#571 #570 delete print
  neclib/coordinates/pointing_error/omu1p85m.py
Labels: bug

#569 #568 settingfile
  neclib/defaults/config.toml
  neclib/defaults/device_setting.toml
Labels: enhancement

#564 #531 dome
  neclib/defaults/config.toml
  neclib/devices/device_base.py
  neclib/devices/encoder/__init__.py
  neclib/devices/encoder/cpz6204.py
  neclib/devices/motor/cpz2724.py
  neclib/devices/motor/cpz7204.py
  neclib/simulators/__init__.py
  neclib/simulators/dome.py
Labels: enhancement

#578 #577 release
  pyproject.toml
Labels: release

#585 #584 fixed bug
  neclib/defaults/NANTEN2_config.toml
  neclib/devices/encoder/cpz6204.py
  neclib/devices/motor/cpz2724.py
Labels: bug

#589 #587 add lan communicator
  neclib/devices/attenuator/a11713b.py
  tests/devices/attenuator/test_a11713b.py
Labels: enhancement

#588 #586 fixed bug
  neclib/defaults/NANTEN2_config.toml
  neclib/devices/motor/cpz2724.py
Labels: bug

#583 #582 add 2724 for drive
  neclib/defaults/NANTEN2_config.toml
  neclib/devices/motor/cpz2724.py
Labels: enhancement
