Repository necst-telescope/neclib, pull requests merged in 2024-08, with the labels that each got.

#591 #590 get speed
  neclib/defaults/NANTEN2_config.toml
  neclib/devices/encoder/cpz6204.py
  neclib/devices/motor/cpz2724.py
Labels: bug

#594 #593 debug
  neclib/defaults/NANTEN2_config.toml
  neclib/defaults/config.toml
  neclib/devices/encoder/cpz6204.py
  neclib/devices/motor/cpz2724.py
Labels: bug

#597 debug
  neclib/defaults/NANTEN2_config.toml
  neclib/devices/motor/cpz2724.py
Labels: bug

#600 Debug 0803
  neclib/devices/encoder/cpz6204.py
  neclib/devices/motor/cpz2724.py
Labels: bug

#604 #603 add drive status
  neclib/defaults/NANTEN2_config.toml
  neclib/devices/motor/cpz2724.py
Labels: enhancement

#605 release
  pyproject.toml
Labels: release

#606 Debug 0805
  neclib/devices/motor/cpz2724.py
Labels: bug

#608 #607 add identifer
  neclib/defaults/NANTEN2_config.toml
  neclib/defaults/config.toml
  neclib/devices/motor/cpz2724.py
Labels: enhancement

#610 #609 release
  pyproject.toml
Labels: release

#612 #611 release
  neclib/defaults/NANTEN2_config.toml
  neclib/defaults/config.toml
  neclib/devices/motor/cpz2724.py
  pyproject.toml
Labels: release

#618 debug
  neclib/devices/encoder/cpz6204.py
Labels: bug

#623 debug_0811
  neclib/defaults/NANTEN2_config.toml
Labels: bug

#624 #598 edit config
  neclib/defaults/NANTEN2_config.toml
Labels: bug

#627 #626 nasco dev
  neclib/defaults/NANTEN2_config.toml
  neclib/devices/attenuator/simulator.py
  neclib/devices/signal_generator/simulator.py
Labels: bug

#630 #629 fix
  neclib/defaults/NANTEN2_config.toml
Labels: bug

#632 debug
  neclib/defaults/NANTEN2_config.toml
Labels: bug

#636 #635 add buffer
  neclib/devices/attenuator/cpz340516.py
  neclib/devices/da_converter/cpz340816.py
Labels: bug

#634 #633 debug
  neclib/defaults/NANTEN2_config.toml
  neclib/devices/motor/cpz7415v.py
Labels: bug

#638 #637 modi
  neclib/devices/attenuator/attenuator_base.py
  neclib/devices/attenuator/cpz340516.py
Labels: bug

#640 #639 quesize
  neclib/defaults/NANTEN2_config.toml
  neclib/defaults/OMU1p85m_config.toml
  neclib/defaults/config.toml
  neclib/devices/spectrometer/xffts.py
Labels: enhancement

#643 #628 debug
  neclib/defaults/NANTEN2_config.toml
Labels: bug

#642 #641 add mode
  neclib/defaults/NANTEN2_config.toml
  neclib/defaults/OMU1p85m_config.toml
  neclib/defaults/config.toml
  neclib/devices/motor/cpz7415v.py
Labels: enhancement

#646 #645 modi config
  neclib/defaults/NANTEN2_config.toml
Labels: bug

#651 #650 modi
  neclib/defaults/NANTEN2_config.toml
  neclib/devices/signal_generator/e8257d.py
Labels: bug
